import type { Metadata } from "next";
import { Geist, Geist_Mono, Sulphur_Point } from "next/font/google";
import "./globals.css";
import "../styles/gradients.css";
import "../styles/button-gradient.css";
import "../styles/parallax-bg.css";
import { Navbar } from "@/components/navbar";

const geistSans = Sulphur_Point({
  variable: "--font-primary",
  subsets: ["latin"],
  weight: ["400"],
  // weight: ["300", "400", "500"], // or just one: weight: "400"
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="parallax-bg" aria-hidden="true" />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
